#include "GPIO.h"

// GPIO 引脚初始化函数
void GPIO_Config(void)
{
	RCC_APB2PeriphClockCmd(LEFTWHEEL_GPIO_CLK, ENABLE);    // 打开时钟
	RCC_APB2PeriphClockCmd(RIGHTWHEEL_GPIO_CLK, ENABLE);
//	RCC_APB2PeriphClockCmd(TRACK_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(SLIDE_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(START_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RED_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(GREEN_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BLUE_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(FRONTSEVEN1_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(FRONTSEVEN2_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(FRONTSEVEN3_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(FRONTSEVEN4_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(FRONTSEVEN5_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(FRONTSEVEN6_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(FRONTSEVEN7_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BACKSEVEN1_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BACKSEVEN2_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BACKSEVEN3_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BACKSEVEN4_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BACKSEVEN5_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BACKSEVEN6_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(BACKSEVEN7_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(LEFTSEVEN1_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(LEFTSEVEN2_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(LEFTSEVEN3_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(LEFTSEVEN4_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(LEFTSEVEN5_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(LEFTSEVEN6_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(LEFTSEVEN7_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RIGHTSEVEN1_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RIGHTSEVEN2_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RIGHTSEVEN3_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RIGHTSEVEN4_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RIGHTSEVEN5_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RIGHTSEVEN6_GPIO_CLK, ENABLE);
	RCC_APB2PeriphClockCmd(RIGHTSEVEN7_GPIO_CLK, ENABLE);
	
	GPIO_InitTypeDef GPIO_InitStruct;                      // 定义初始化结构体
	
	GPIO_InitStruct.GPIO_Pin = LEFTWHEEL_GPIO_PIN;         // 修改初始化结构体数据
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_Out_OD;          // 开漏输出模式（控制电机转向要开漏输出）
	GPIO_InitStruct.GPIO_Speed = GPIO_Speed_50MHz;
	GPIO_Init(LEFTWHEEL_GPIO_PORT, &GPIO_InitStruct);      // 初始化结构体
	
	GPIO_InitStruct.GPIO_Pin = RIGHTWHEEL_GPIO_PIN;
	GPIO_Init(RIGHTWHEEL_GPIO_PORT, &GPIO_InitStruct);
	
//	GPIO_InitStruct.GPIO_Pin = TRACK_GPIO_PIN;
//	GPIO_Init(TRACK_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Pin = SLIDE_GPIO_PIN;
	GPIO_Init(SLIDE_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IN_FLOATING;     // 浮空输入模式（按钮信号输入要浮空输入）
	GPIO_InitStruct.GPIO_Pin = START_GPIO_PIN;
	GPIO_Init(START_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_Out_PP;          // 推挽输出模式（控制普通IO输出要推挽输出）
	GPIO_InitStruct.GPIO_Pin = RED_GPIO_PIN;
	GPIO_Init(RED_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Pin = GREEN_GPIO_PIN;
	GPIO_Init(GREEN_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Pin = BLUE_GPIO_PIN;
	GPIO_Init(BLUE_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Mode = GPIO_Mode_IN_FLOATING;     // 浮空输入模式（七路信号输入要浮空输入）
	GPIO_InitStruct.GPIO_Pin = FRONTSEVEN1_GPIO_PIN;
	GPIO_Init(FRONTSEVEN1_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = FRONTSEVEN2_GPIO_PIN;
	GPIO_Init(FRONTSEVEN2_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = FRONTSEVEN3_GPIO_PIN;
	GPIO_Init(FRONTSEVEN3_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = FRONTSEVEN4_GPIO_PIN;
	GPIO_Init(FRONTSEVEN4_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = FRONTSEVEN5_GPIO_PIN;
	GPIO_Init(FRONTSEVEN5_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = FRONTSEVEN6_GPIO_PIN;
	GPIO_Init(FRONTSEVEN6_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = FRONTSEVEN7_GPIO_PIN;
	GPIO_Init(FRONTSEVEN7_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Pin = BACKSEVEN1_GPIO_PIN;
	GPIO_Init(BACKSEVEN1_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = BACKSEVEN2_GPIO_PIN;
	GPIO_Init(BACKSEVEN2_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = BACKSEVEN3_GPIO_PIN;
	GPIO_Init(BACKSEVEN3_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = BACKSEVEN4_GPIO_PIN;
	GPIO_Init(BACKSEVEN4_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = BACKSEVEN5_GPIO_PIN;
	GPIO_Init(BACKSEVEN5_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = BACKSEVEN6_GPIO_PIN;
	GPIO_Init(BACKSEVEN6_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = BACKSEVEN7_GPIO_PIN;
	GPIO_Init(BACKSEVEN7_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Pin = LEFTSEVEN1_GPIO_PIN;
	GPIO_Init(LEFTSEVEN1_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = LEFTSEVEN2_GPIO_PIN;
	GPIO_Init(LEFTSEVEN2_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = LEFTSEVEN3_GPIO_PIN;
	GPIO_Init(LEFTSEVEN3_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = LEFTSEVEN4_GPIO_PIN;
	GPIO_Init(LEFTSEVEN4_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = LEFTSEVEN5_GPIO_PIN;
	GPIO_Init(LEFTSEVEN5_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = LEFTSEVEN6_GPIO_PIN;
	GPIO_Init(LEFTSEVEN6_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = LEFTSEVEN7_GPIO_PIN;
	GPIO_Init(LEFTSEVEN7_GPIO_PORT, &GPIO_InitStruct);
	
	GPIO_InitStruct.GPIO_Pin = RIGHTSEVEN1_GPIO_PIN;
	GPIO_Init(RIGHTSEVEN1_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = RIGHTSEVEN2_GPIO_PIN;
	GPIO_Init(RIGHTSEVEN2_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = RIGHTSEVEN3_GPIO_PIN;
	GPIO_Init(RIGHTSEVEN3_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = RIGHTSEVEN4_GPIO_PIN;
	GPIO_Init(RIGHTSEVEN4_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = RIGHTSEVEN5_GPIO_PIN;
	GPIO_Init(RIGHTSEVEN5_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = RIGHTSEVEN6_GPIO_PIN;
	GPIO_Init(RIGHTSEVEN6_GPIO_PORT, &GPIO_InitStruct);
	GPIO_InitStruct.GPIO_Pin = RIGHTSEVEN7_GPIO_PIN;
	GPIO_Init(RIGHTSEVEN7_GPIO_PORT, &GPIO_InitStruct);
	
//	GPIO_SetBits(LEFTWHEEL_GPIO_PORT, LEFTWHEEL_GPIO_PIN); // 全部输出低电平
//  GPIO_SetBits(RIGHTWHEEL_GPIO_PORT, RIGHTWHEEL_GPIO_PIN);
//	GPIO_SetBits(TRACK_GPIO_PORT, TRACK_GPIO_PIN);
//	GPIO_SetBits(SLIDE_GPIO_PORT, SLIDE_GPIO_PIN);
  GPIO_SetBits(RED_GPIO_PORT, RED_GPIO_PIN);
	GPIO_SetBits(GREEN_GPIO_PORT, GREEN_GPIO_PIN);
	GPIO_SetBits(BLUE_GPIO_PORT, BLUE_GPIO_PIN);
}


// GPIO 引脚输出高电平
void GPIO_High(GPIO_TypeDef * port, uint16_t pin)
{
	GPIO_SetBits(port, pin);
}

// GPIO 引脚输出低电平
void GPIO_Low(GPIO_TypeDef * port, uint16_t pin)
{
	GPIO_ResetBits(port, pin);
}

// GPIO 引脚读取
int GPIO_Read(GPIO_TypeDef * port, uint16_t pin)
{
	int ReadValue;
	ReadValue = GPIO_ReadInputDataBit(port, pin);
	
	return ReadValue;
}


// 七路信号读取。形参为哪个七路（1-front；2-back；3-left；4-right）
int Seven_Read(int s, int n){
	int one, two, three, four, five, six, seven = 0;
  switch(s){
		case 1:{
			switch(n){
			  case 1: return GPIO_Read(FRONTSEVEN1_GPIO_PORT, FRONTSEVEN1_GPIO_PIN); break;
				case 2: return GPIO_Read(FRONTSEVEN2_GPIO_PORT, FRONTSEVEN2_GPIO_PIN); break;
			  case 3: return GPIO_Read(FRONTSEVEN3_GPIO_PORT, FRONTSEVEN3_GPIO_PIN); break;
			  case 4: return GPIO_Read(FRONTSEVEN4_GPIO_PORT, FRONTSEVEN4_GPIO_PIN); break;
			  case 5: return GPIO_Read(FRONTSEVEN5_GPIO_PORT, FRONTSEVEN5_GPIO_PIN); break;
			  case 6: return GPIO_Read(FRONTSEVEN6_GPIO_PORT, FRONTSEVEN6_GPIO_PIN); break;
			  case 7: return GPIO_Read(FRONTSEVEN7_GPIO_PORT, FRONTSEVEN7_GPIO_PIN); break;
			}
		}
		case 2:{
			switch(n){
			  case 1: return GPIO_Read(BACKSEVEN1_GPIO_PORT, BACKSEVEN1_GPIO_PIN); break;
				case 2: return GPIO_Read(BACKSEVEN2_GPIO_PORT, BACKSEVEN2_GPIO_PIN); break;
			  case 3: return GPIO_Read(BACKSEVEN3_GPIO_PORT, BACKSEVEN3_GPIO_PIN); break;
			  case 4: return GPIO_Read(BACKSEVEN4_GPIO_PORT, BACKSEVEN4_GPIO_PIN); break;
			  case 5: return GPIO_Read(BACKSEVEN5_GPIO_PORT, BACKSEVEN5_GPIO_PIN); break;
			  case 6: return GPIO_Read(BACKSEVEN6_GPIO_PORT, BACKSEVEN6_GPIO_PIN); break;
			  case 7: return GPIO_Read(BACKSEVEN7_GPIO_PORT, BACKSEVEN7_GPIO_PIN); break;
			}
		}
		case 3:{
			switch(n){
			  case 1: return GPIO_Read(LEFTSEVEN1_GPIO_PORT, LEFTSEVEN1_GPIO_PIN); break;
				case 2: return GPIO_Read(LEFTSEVEN2_GPIO_PORT, LEFTSEVEN2_GPIO_PIN); break;
			  case 3: return GPIO_Read(LEFTSEVEN3_GPIO_PORT, LEFTSEVEN3_GPIO_PIN); break;
			  case 4: return GPIO_Read(LEFTSEVEN4_GPIO_PORT, LEFTSEVEN4_GPIO_PIN); break;
			  case 5: return GPIO_Read(LEFTSEVEN5_GPIO_PORT, LEFTSEVEN5_GPIO_PIN); break;
			  case 6: return GPIO_Read(LEFTSEVEN6_GPIO_PORT, LEFTSEVEN6_GPIO_PIN); break;
			  case 7: return GPIO_Read(LEFTSEVEN7_GPIO_PORT, LEFTSEVEN7_GPIO_PIN); break;
			}
		}
		case 4:{
			switch(n){
			  case 1: return GPIO_Read(RIGHTSEVEN1_GPIO_PORT, RIGHTSEVEN1_GPIO_PIN); break;
				case 2: return GPIO_Read(RIGHTSEVEN2_GPIO_PORT, RIGHTSEVEN2_GPIO_PIN); break;
			  case 3: return GPIO_Read(RIGHTSEVEN3_GPIO_PORT, RIGHTSEVEN3_GPIO_PIN); break;
			  case 4: return GPIO_Read(RIGHTSEVEN4_GPIO_PORT, RIGHTSEVEN4_GPIO_PIN); break;
			  case 5: return GPIO_Read(RIGHTSEVEN5_GPIO_PORT, RIGHTSEVEN5_GPIO_PIN); break;
			  case 6: return GPIO_Read(RIGHTSEVEN6_GPIO_PORT, RIGHTSEVEN6_GPIO_PIN); break;
			  case 7: return GPIO_Read(RIGHTSEVEN7_GPIO_PORT, RIGHTSEVEN7_GPIO_PIN); break;
			}
		}
		default: return 0; break;
	}
}